title: Le Quyet Tien
subtitle: Software Developer
description: >- # this means to ignore newlines until "baseurl:"
  lequyettien.it@gmail.com

url: "https://lequyettien.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Le Quyet Tien
author_bio: Hello, My Name is Le Quyet Tien. I love to Code and Design.
author_email: "lequyettien.it@gmail.com"
author_location: Vietnam
author_website_url: "https://lequyettien.github.io"

author_work_experiences: 
            - company_name: EZ Active Vietnam
              company_logo: ezactive.png
              company_url: https://www.ezactive.com
              designation: Software Developer
              description: Worked on various EZ Active Vietnam
              visibility: true

author_education_details:
              - college_logo: ntu.png
                college_name: Nha Trang University
                college_url: https://ntu.edu.vn
                college_degree: IT Engineer
                description: Bachelor's degree, Infomation Technology
                visibility: true

author_project_details:
              - project_thumbnail: js.png
                project_title: HKFC - Junior Soccer
                project_description: Wordpress, Season Registration, Club Management
                project_url: https://www.hkfcjuniorsoccer.com/
                visibility: true
              - project_thumbnail: hkjfl.png
                project_title: Hong Kong Junior Football League
                project_description: Wordpress, League Registration, League Management
                project_url: https://www.hkjfl.com/
                visibility: true
              - project_thumbnail: vf.png
                project_title: Valley Fort
                project_description: Season Registration, Club Management
                project_url: https://valleyfort.com/
                visibility: true
              - project_thumbnail: sgb.png
                project_title: SG Basketball
                project_description: Court Booking, Academy Registration, CBL League Registration
                project_url: https://sgbasketball.com/
                visibility: true

# social links
twitter_username: LeQuyetTien74
github_username:  LeQuyetTien
facebook_username: LeQuyetTien74
linkedin_username: LeQuyetTien
behance_username: LeQuyetTien
instagram_username: LeQuyetTien74
medium_username: LeQuyetTien74
telegram_username: LeQuyetTien
dribbble_username: LeQuyetTien
flickr_username: LeQuyetTien

#for comments using disqus
disqus_shortname: LeQuyetTien

# wakatime username (coding activity)
wakatime_username: LeQuyetTien

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us19.list-manage.com/subscribe/post?u=e4bdc3fc8b853af82c02414cc&id=b153cedd6a

# formspree (contact form)
formspree_email: lequyettien.it@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-158658777-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build